##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/SummittDweller/1926-miriam-mcfate-journal

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Miriam McFate Travel Journal - 1926
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Imagine traveling 2800 miles in a home-made camper with 9 occupants... nearly 100 years ago!
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "In 1926 my grandparents, Clarence and Miriam Abia McFate of rural Poweshiek County, Iowa, built a 'home' on the back of what I believe was a Model TT Ford truck, and moved the family (3 adults, 5 children and a dog) to Long Beach, California.  They traveled 2800+ miles over the span of 41 days, about 35 of those moving from camp-to-camp.  This collection is grandma's daily journal plus whatever supporting material I could dig up. <p>Be advised, this is a work-in-progress and still contains language that may be offensive to some. My grandmother meant no harm so please don't be offended; I will try my best to faithfully sanitize the language as this collection comes together."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: iowa, illinois, missouri, arkansas, texas, new mexico, arizona, california, 1926, travel
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Mark A. McFate

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: "McFate-Travel-Diary-CollectionBuilder-1926-Journal"
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: SummittDweller.com
organization-link: https://blog.SummittDweller.com/
organization-logo-banner: https://mcfate.blob.core.windows.net/1926/Summitt-Services-logo.png
organization-logo-nav: https://mcfate.blob.core.windows.net/1926/Summitt-Services-logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
